name: CI/CD

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy to GitHub Pages
        run: |
          # Replace these commands with your actual build and deploy steps
          # For example, if you're building a static site and deploying to GitHub Pages:
          # npm install
          # npm run build
          # gh-pages -d dist

      - name: Deployed to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Deploy the built files to GitHub Pages
          # This uses the GITHUB_TOKEN secret for authentication
          # For example, using the gh-pages package:
          # npm install -g gh-pages
          # gh-pages -d dist

